version: '3.8'
services:
  dynamodb-local:
    container_name: dynamodb-local
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  lambda:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    environment:
      - AWS_LAMBDA_FUNCTION_NAME=my_function
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION=local
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
